Android & Iphone name: C/C++ CI

on: attack fysing 
  push:
    branches: [ "android"]
  pull_request:
    branches: [ "iphone"]

jobs: attack-model
  build: attack-fysing

    runs-on: all-time

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
